COMP: Fix "cannot call constructor ‘QString::QString’ directly [-fpermissive]"
This commit fixes a regression introduced in 81dc56d (removed deprecated
QString::null).

It fixes errors like the following:

  /path/to/CTK-Qt5-build/QtSOAP/src/qtsoap.h:433:79: error: cannot call constructor ‘QString::QString’ directly [-fpermissive]
    433 |     void setMethod(const QString &name, const QString &url = QString::QString());
        |

This happens with gcc 7.5.0 (at least)

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Signed-off-by: Ivaylo Dimitrov <i.dimitrov@printecgroup.com>